name: vcf_to_custom_haplo_conversion

on:
  push:
    branches:
      dev

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pipeline code
        uses: actions/checkout@v4

      - name: Set up python 3.10.12
        uses: mamba-org/setup-micromamba@v1
        with: 
          micromamba-version: '1.3.1-0'
          environment-file: environment.yml
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'

      - name: Run python script with test data
        run: python noob2.py OUT_VCF_BEAGLE4_ALL_AutoSom21b_Chr28.TxT.vcf.gz output_1 40
        shell: bash -el {0} 
